//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QueNoSePase.API.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://servicioswebsms4.efibus.com.ar/ServicioWebHorariosProximos.asmx")]
        public string QueNoSePase_WebDataClient_ServicioWebHorariosProximos {
            get {
                return ((string)(this["QueNoSePase_WebDataClient_ServicioWebHorariosProximos"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://servicioswebsms.efibus.com.ar/ServicioWebHorariosProximos.asmx")]
        public string QueNoSePase_API_ar_com_efibus_servicioswebsms_ServicioWebHorariosProximos {
            get {
                return ((string)(this["QueNoSePase_API_ar_com_efibus_servicioswebsms_ServicioWebHorariosProximos"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://swandroidcuandollegasmp01.efibus.com.ar/Paradas.asmx")]
        public string QueNoSePase_API_swandroidcuandollegasmp_Paradas {
            get {
                return ((string)(this["QueNoSePase_API_swandroidcuandollegasmp_Paradas"]));
            }
        }
    }
}
