//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace QueNoSePase.API.swandroidcuandollegasmp {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ParadasSoap", Namespace="http://tempuri.org/")]
    public partial class Paradas : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private UserDetails userDetailsValueField;
        
        private System.Threading.SendOrPostCallback RecuperarLocalidadesPorEntidadOperationCompleted;
        
        private System.Threading.SendOrPostCallback RecuperarLineaPorLocalidadOperationCompleted;
        
        private System.Threading.SendOrPostCallback RecuperarLineaPorEntidadOperationCompleted;
        
        private System.Threading.SendOrPostCallback RecuperarLineasPorCodigoEmpresaOperationCompleted;
        
        private System.Threading.SendOrPostCallback RecuperarLineaPorCuandoLlegaOperationCompleted;
        
        private System.Threading.SendOrPostCallback RecuperarCallesPrincipalPorLineaOperationCompleted;
        
        private System.Threading.SendOrPostCallback RecuperarInterseccionPorLineaYCalleOperationCompleted;
        
        private System.Threading.SendOrPostCallback RecuperarParadasPorCalleEInterseccionOperationCompleted;
        
        private System.Threading.SendOrPostCallback RecuperarParadasPorLineaCalleEInterseccionOperationCompleted;
        
        private System.Threading.SendOrPostCallback RecuperarParadasConBanderaPorLineaCalleEInterseccionOperationCompleted;
        
        private System.Threading.SendOrPostCallback RecuperarProximosArribosOperationCompleted;
        
        private System.Threading.SendOrPostCallback RecuperarParadasPorLineaParaCuandoLlegaOperationCompleted;
        
        private System.Threading.SendOrPostCallback RecuperarProximosArribosCLCompletoOperationCompleted;
        
        private System.Threading.SendOrPostCallback RecuperarProximosArribosSMPOperationCompleted;
        
        private System.Threading.SendOrPostCallback RecuperarRecorridoParaMapaPorEntidadYLineaOperationCompleted;
        
        private System.Threading.SendOrPostCallback RecuperarRecorridoParaMapaAbrevYAmpliPorEntidadYLineaOperationCompleted;
        
        private System.Threading.SendOrPostCallback RecuperarTodasEmpresasAMigrarOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Paradas() {
            this.Url = global::QueNoSePase.API.Properties.Settings.Default.QueNoSePase_API_swandroidcuandollegasmp_Paradas;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public UserDetails UserDetailsValue {
            get {
                return this.userDetailsValueField;
            }
            set {
                this.userDetailsValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event RecuperarLocalidadesPorEntidadCompletedEventHandler RecuperarLocalidadesPorEntidadCompleted;
        
        /// <remarks/>
        public event RecuperarLineaPorLocalidadCompletedEventHandler RecuperarLineaPorLocalidadCompleted;
        
        /// <remarks/>
        public event RecuperarLineaPorEntidadCompletedEventHandler RecuperarLineaPorEntidadCompleted;
        
        /// <remarks/>
        public event RecuperarLineasPorCodigoEmpresaCompletedEventHandler RecuperarLineasPorCodigoEmpresaCompleted;
        
        /// <remarks/>
        public event RecuperarLineaPorCuandoLlegaCompletedEventHandler RecuperarLineaPorCuandoLlegaCompleted;
        
        /// <remarks/>
        public event RecuperarCallesPrincipalPorLineaCompletedEventHandler RecuperarCallesPrincipalPorLineaCompleted;
        
        /// <remarks/>
        public event RecuperarInterseccionPorLineaYCalleCompletedEventHandler RecuperarInterseccionPorLineaYCalleCompleted;
        
        /// <remarks/>
        public event RecuperarParadasPorCalleEInterseccionCompletedEventHandler RecuperarParadasPorCalleEInterseccionCompleted;
        
        /// <remarks/>
        public event RecuperarParadasPorLineaCalleEInterseccionCompletedEventHandler RecuperarParadasPorLineaCalleEInterseccionCompleted;
        
        /// <remarks/>
        public event RecuperarParadasConBanderaPorLineaCalleEInterseccionCompletedEventHandler RecuperarParadasConBanderaPorLineaCalleEInterseccionCompleted;
        
        /// <remarks/>
        public event RecuperarProximosArribosCompletedEventHandler RecuperarProximosArribosCompleted;
        
        /// <remarks/>
        public event RecuperarParadasPorLineaParaCuandoLlegaCompletedEventHandler RecuperarParadasPorLineaParaCuandoLlegaCompleted;
        
        /// <remarks/>
        public event RecuperarProximosArribosCLCompletoCompletedEventHandler RecuperarProximosArribosCLCompletoCompleted;
        
        /// <remarks/>
        public event RecuperarProximosArribosSMPCompletedEventHandler RecuperarProximosArribosSMPCompleted;
        
        /// <remarks/>
        public event RecuperarRecorridoParaMapaPorEntidadYLineaCompletedEventHandler RecuperarRecorridoParaMapaPorEntidadYLineaCompleted;
        
        /// <remarks/>
        public event RecuperarRecorridoParaMapaAbrevYAmpliPorEntidadYLineaCompletedEventHandler RecuperarRecorridoParaMapaAbrevYAmpliPorEntidadYLineaCompleted;
        
        /// <remarks/>
        public event RecuperarTodasEmpresasAMigrarCompletedEventHandler RecuperarTodasEmpresasAMigrarCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("UserDetailsValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RecuperarLocalidadesPorEntidad", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Localidad[] RecuperarLocalidadesPorEntidad(int codEntidad) {
            object[] results = this.Invoke("RecuperarLocalidadesPorEntidad", new object[] {
                        codEntidad});
            return ((Localidad[])(results[0]));
        }
        
        /// <remarks/>
        public void RecuperarLocalidadesPorEntidadAsync(int codEntidad) {
            this.RecuperarLocalidadesPorEntidadAsync(codEntidad, null);
        }
        
        /// <remarks/>
        public void RecuperarLocalidadesPorEntidadAsync(int codEntidad, object userState) {
            if ((this.RecuperarLocalidadesPorEntidadOperationCompleted == null)) {
                this.RecuperarLocalidadesPorEntidadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRecuperarLocalidadesPorEntidadOperationCompleted);
            }
            this.InvokeAsync("RecuperarLocalidadesPorEntidad", new object[] {
                        codEntidad}, this.RecuperarLocalidadesPorEntidadOperationCompleted, userState);
        }
        
        private void OnRecuperarLocalidadesPorEntidadOperationCompleted(object arg) {
            if ((this.RecuperarLocalidadesPorEntidadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RecuperarLocalidadesPorEntidadCompleted(this, new RecuperarLocalidadesPorEntidadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("UserDetailsValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RecuperarLineaPorLocalidad", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TresPropiedades[] RecuperarLineaPorLocalidad(string localidad, string provincia, string pais) {
            object[] results = this.Invoke("RecuperarLineaPorLocalidad", new object[] {
                        localidad,
                        provincia,
                        pais});
            return ((TresPropiedades[])(results[0]));
        }
        
        /// <remarks/>
        public void RecuperarLineaPorLocalidadAsync(string localidad, string provincia, string pais) {
            this.RecuperarLineaPorLocalidadAsync(localidad, provincia, pais, null);
        }
        
        /// <remarks/>
        public void RecuperarLineaPorLocalidadAsync(string localidad, string provincia, string pais, object userState) {
            if ((this.RecuperarLineaPorLocalidadOperationCompleted == null)) {
                this.RecuperarLineaPorLocalidadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRecuperarLineaPorLocalidadOperationCompleted);
            }
            this.InvokeAsync("RecuperarLineaPorLocalidad", new object[] {
                        localidad,
                        provincia,
                        pais}, this.RecuperarLineaPorLocalidadOperationCompleted, userState);
        }
        
        private void OnRecuperarLineaPorLocalidadOperationCompleted(object arg) {
            if ((this.RecuperarLineaPorLocalidadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RecuperarLineaPorLocalidadCompleted(this, new RecuperarLineaPorLocalidadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("UserDetailsValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RecuperarLineaPorEntidad", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Simple[] RecuperarLineaPorEntidad(int codigoEntidad) {
            object[] results = this.Invoke("RecuperarLineaPorEntidad", new object[] {
                        codigoEntidad});
            return ((Simple[])(results[0]));
        }
        
        /// <remarks/>
        public void RecuperarLineaPorEntidadAsync(int codigoEntidad) {
            this.RecuperarLineaPorEntidadAsync(codigoEntidad, null);
        }
        
        /// <remarks/>
        public void RecuperarLineaPorEntidadAsync(int codigoEntidad, object userState) {
            if ((this.RecuperarLineaPorEntidadOperationCompleted == null)) {
                this.RecuperarLineaPorEntidadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRecuperarLineaPorEntidadOperationCompleted);
            }
            this.InvokeAsync("RecuperarLineaPorEntidad", new object[] {
                        codigoEntidad}, this.RecuperarLineaPorEntidadOperationCompleted, userState);
        }
        
        private void OnRecuperarLineaPorEntidadOperationCompleted(object arg) {
            if ((this.RecuperarLineaPorEntidadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RecuperarLineaPorEntidadCompleted(this, new RecuperarLineaPorEntidadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("UserDetailsValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RecuperarLineasPorCodigoEmpresa", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Simple[] RecuperarLineasPorCodigoEmpresa(int codigoEmpresa) {
            object[] results = this.Invoke("RecuperarLineasPorCodigoEmpresa", new object[] {
                        codigoEmpresa});
            return ((Simple[])(results[0]));
        }
        
        /// <remarks/>
        public void RecuperarLineasPorCodigoEmpresaAsync(int codigoEmpresa) {
            this.RecuperarLineasPorCodigoEmpresaAsync(codigoEmpresa, null);
        }
        
        /// <remarks/>
        public void RecuperarLineasPorCodigoEmpresaAsync(int codigoEmpresa, object userState) {
            if ((this.RecuperarLineasPorCodigoEmpresaOperationCompleted == null)) {
                this.RecuperarLineasPorCodigoEmpresaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRecuperarLineasPorCodigoEmpresaOperationCompleted);
            }
            this.InvokeAsync("RecuperarLineasPorCodigoEmpresa", new object[] {
                        codigoEmpresa}, this.RecuperarLineasPorCodigoEmpresaOperationCompleted, userState);
        }
        
        private void OnRecuperarLineasPorCodigoEmpresaOperationCompleted(object arg) {
            if ((this.RecuperarLineasPorCodigoEmpresaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RecuperarLineasPorCodigoEmpresaCompleted(this, new RecuperarLineasPorCodigoEmpresaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("UserDetailsValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RecuperarLineaPorCuandoLlega", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TresPropiedades[] RecuperarLineaPorCuandoLlega(int codigoCuandoLlega) {
            object[] results = this.Invoke("RecuperarLineaPorCuandoLlega", new object[] {
                        codigoCuandoLlega});
            return ((TresPropiedades[])(results[0]));
        }
        
        /// <remarks/>
        public void RecuperarLineaPorCuandoLlegaAsync(int codigoCuandoLlega) {
            this.RecuperarLineaPorCuandoLlegaAsync(codigoCuandoLlega, null);
        }
        
        /// <remarks/>
        public void RecuperarLineaPorCuandoLlegaAsync(int codigoCuandoLlega, object userState) {
            if ((this.RecuperarLineaPorCuandoLlegaOperationCompleted == null)) {
                this.RecuperarLineaPorCuandoLlegaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRecuperarLineaPorCuandoLlegaOperationCompleted);
            }
            this.InvokeAsync("RecuperarLineaPorCuandoLlega", new object[] {
                        codigoCuandoLlega}, this.RecuperarLineaPorCuandoLlegaOperationCompleted, userState);
        }
        
        private void OnRecuperarLineaPorCuandoLlegaOperationCompleted(object arg) {
            if ((this.RecuperarLineaPorCuandoLlegaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RecuperarLineaPorCuandoLlegaCompleted(this, new RecuperarLineaPorCuandoLlegaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("UserDetailsValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RecuperarCallesPrincipalPorLinea", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Simple[] RecuperarCallesPrincipalPorLinea(int codLinea) {
            object[] results = this.Invoke("RecuperarCallesPrincipalPorLinea", new object[] {
                        codLinea});
            return ((Simple[])(results[0]));
        }
        
        /// <remarks/>
        public void RecuperarCallesPrincipalPorLineaAsync(int codLinea) {
            this.RecuperarCallesPrincipalPorLineaAsync(codLinea, null);
        }
        
        /// <remarks/>
        public void RecuperarCallesPrincipalPorLineaAsync(int codLinea, object userState) {
            if ((this.RecuperarCallesPrincipalPorLineaOperationCompleted == null)) {
                this.RecuperarCallesPrincipalPorLineaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRecuperarCallesPrincipalPorLineaOperationCompleted);
            }
            this.InvokeAsync("RecuperarCallesPrincipalPorLinea", new object[] {
                        codLinea}, this.RecuperarCallesPrincipalPorLineaOperationCompleted, userState);
        }
        
        private void OnRecuperarCallesPrincipalPorLineaOperationCompleted(object arg) {
            if ((this.RecuperarCallesPrincipalPorLineaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RecuperarCallesPrincipalPorLineaCompleted(this, new RecuperarCallesPrincipalPorLineaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("UserDetailsValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RecuperarInterseccionPorLineaYCalle", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Simple[] RecuperarInterseccionPorLineaYCalle(int codLinea, int codCalle) {
            object[] results = this.Invoke("RecuperarInterseccionPorLineaYCalle", new object[] {
                        codLinea,
                        codCalle});
            return ((Simple[])(results[0]));
        }
        
        /// <remarks/>
        public void RecuperarInterseccionPorLineaYCalleAsync(int codLinea, int codCalle) {
            this.RecuperarInterseccionPorLineaYCalleAsync(codLinea, codCalle, null);
        }
        
        /// <remarks/>
        public void RecuperarInterseccionPorLineaYCalleAsync(int codLinea, int codCalle, object userState) {
            if ((this.RecuperarInterseccionPorLineaYCalleOperationCompleted == null)) {
                this.RecuperarInterseccionPorLineaYCalleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRecuperarInterseccionPorLineaYCalleOperationCompleted);
            }
            this.InvokeAsync("RecuperarInterseccionPorLineaYCalle", new object[] {
                        codLinea,
                        codCalle}, this.RecuperarInterseccionPorLineaYCalleOperationCompleted, userState);
        }
        
        private void OnRecuperarInterseccionPorLineaYCalleOperationCompleted(object arg) {
            if ((this.RecuperarInterseccionPorLineaYCalleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RecuperarInterseccionPorLineaYCalleCompleted(this, new RecuperarInterseccionPorLineaYCalleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("UserDetailsValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RecuperarParadasPorCalleEInterseccion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Parada[] RecuperarParadasPorCalleEInterseccion(int codCalle, int codInterseccion) {
            object[] results = this.Invoke("RecuperarParadasPorCalleEInterseccion", new object[] {
                        codCalle,
                        codInterseccion});
            return ((Parada[])(results[0]));
        }
        
        /// <remarks/>
        public void RecuperarParadasPorCalleEInterseccionAsync(int codCalle, int codInterseccion) {
            this.RecuperarParadasPorCalleEInterseccionAsync(codCalle, codInterseccion, null);
        }
        
        /// <remarks/>
        public void RecuperarParadasPorCalleEInterseccionAsync(int codCalle, int codInterseccion, object userState) {
            if ((this.RecuperarParadasPorCalleEInterseccionOperationCompleted == null)) {
                this.RecuperarParadasPorCalleEInterseccionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRecuperarParadasPorCalleEInterseccionOperationCompleted);
            }
            this.InvokeAsync("RecuperarParadasPorCalleEInterseccion", new object[] {
                        codCalle,
                        codInterseccion}, this.RecuperarParadasPorCalleEInterseccionOperationCompleted, userState);
        }
        
        private void OnRecuperarParadasPorCalleEInterseccionOperationCompleted(object arg) {
            if ((this.RecuperarParadasPorCalleEInterseccionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RecuperarParadasPorCalleEInterseccionCompleted(this, new RecuperarParadasPorCalleEInterseccionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("UserDetailsValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RecuperarParadasPorLineaCalleEInterseccion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Parada[] RecuperarParadasPorLineaCalleEInterseccion(int codLinea, int codCalle, int codInterseccion) {
            object[] results = this.Invoke("RecuperarParadasPorLineaCalleEInterseccion", new object[] {
                        codLinea,
                        codCalle,
                        codInterseccion});
            return ((Parada[])(results[0]));
        }
        
        /// <remarks/>
        public void RecuperarParadasPorLineaCalleEInterseccionAsync(int codLinea, int codCalle, int codInterseccion) {
            this.RecuperarParadasPorLineaCalleEInterseccionAsync(codLinea, codCalle, codInterseccion, null);
        }
        
        /// <remarks/>
        public void RecuperarParadasPorLineaCalleEInterseccionAsync(int codLinea, int codCalle, int codInterseccion, object userState) {
            if ((this.RecuperarParadasPorLineaCalleEInterseccionOperationCompleted == null)) {
                this.RecuperarParadasPorLineaCalleEInterseccionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRecuperarParadasPorLineaCalleEInterseccionOperationCompleted);
            }
            this.InvokeAsync("RecuperarParadasPorLineaCalleEInterseccion", new object[] {
                        codLinea,
                        codCalle,
                        codInterseccion}, this.RecuperarParadasPorLineaCalleEInterseccionOperationCompleted, userState);
        }
        
        private void OnRecuperarParadasPorLineaCalleEInterseccionOperationCompleted(object arg) {
            if ((this.RecuperarParadasPorLineaCalleEInterseccionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RecuperarParadasPorLineaCalleEInterseccionCompleted(this, new RecuperarParadasPorLineaCalleEInterseccionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("UserDetailsValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RecuperarParadasConBanderaPorLineaCalleEInterseccion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ParadaConBandera[] RecuperarParadasConBanderaPorLineaCalleEInterseccion(int codLinea, int codCalle, int codInterseccion) {
            object[] results = this.Invoke("RecuperarParadasConBanderaPorLineaCalleEInterseccion", new object[] {
                        codLinea,
                        codCalle,
                        codInterseccion});
            return ((ParadaConBandera[])(results[0]));
        }
        
        /// <remarks/>
        public void RecuperarParadasConBanderaPorLineaCalleEInterseccionAsync(int codLinea, int codCalle, int codInterseccion) {
            this.RecuperarParadasConBanderaPorLineaCalleEInterseccionAsync(codLinea, codCalle, codInterseccion, null);
        }
        
        /// <remarks/>
        public void RecuperarParadasConBanderaPorLineaCalleEInterseccionAsync(int codLinea, int codCalle, int codInterseccion, object userState) {
            if ((this.RecuperarParadasConBanderaPorLineaCalleEInterseccionOperationCompleted == null)) {
                this.RecuperarParadasConBanderaPorLineaCalleEInterseccionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRecuperarParadasConBanderaPorLineaCalleEInterseccionOperationCompleted);
            }
            this.InvokeAsync("RecuperarParadasConBanderaPorLineaCalleEInterseccion", new object[] {
                        codLinea,
                        codCalle,
                        codInterseccion}, this.RecuperarParadasConBanderaPorLineaCalleEInterseccionOperationCompleted, userState);
        }
        
        private void OnRecuperarParadasConBanderaPorLineaCalleEInterseccionOperationCompleted(object arg) {
            if ((this.RecuperarParadasConBanderaPorLineaCalleEInterseccionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RecuperarParadasConBanderaPorLineaCalleEInterseccionCompleted(this, new RecuperarParadasConBanderaPorLineaCalleEInterseccionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("UserDetailsValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RecuperarProximosArribos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ProximoArribo[] RecuperarProximosArribos(string identificadorParada, int codigoLineaParada, int codigoAplicacion, int codigoEntidad, string localidad) {
            object[] results = this.Invoke("RecuperarProximosArribos", new object[] {
                        identificadorParada,
                        codigoLineaParada,
                        codigoAplicacion,
                        codigoEntidad,
                        localidad});
            return ((ProximoArribo[])(results[0]));
        }
        
        /// <remarks/>
        public void RecuperarProximosArribosAsync(string identificadorParada, int codigoLineaParada, int codigoAplicacion, int codigoEntidad, string localidad) {
            this.RecuperarProximosArribosAsync(identificadorParada, codigoLineaParada, codigoAplicacion, codigoEntidad, localidad, null);
        }
        
        /// <remarks/>
        public void RecuperarProximosArribosAsync(string identificadorParada, int codigoLineaParada, int codigoAplicacion, int codigoEntidad, string localidad, object userState) {
            if ((this.RecuperarProximosArribosOperationCompleted == null)) {
                this.RecuperarProximosArribosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRecuperarProximosArribosOperationCompleted);
            }
            this.InvokeAsync("RecuperarProximosArribos", new object[] {
                        identificadorParada,
                        codigoLineaParada,
                        codigoAplicacion,
                        codigoEntidad,
                        localidad}, this.RecuperarProximosArribosOperationCompleted, userState);
        }
        
        private void OnRecuperarProximosArribosOperationCompleted(object arg) {
            if ((this.RecuperarProximosArribosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RecuperarProximosArribosCompleted(this, new RecuperarProximosArribosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("UserDetailsValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RecuperarParadasPorLineaParaCuandoLlega", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ParadaCompleta[] RecuperarParadasPorLineaParaCuandoLlega(int codLinea) {
            object[] results = this.Invoke("RecuperarParadasPorLineaParaCuandoLlega", new object[] {
                        codLinea});
            return ((ParadaCompleta[])(results[0]));
        }
        
        /// <remarks/>
        public void RecuperarParadasPorLineaParaCuandoLlegaAsync(int codLinea) {
            this.RecuperarParadasPorLineaParaCuandoLlegaAsync(codLinea, null);
        }
        
        /// <remarks/>
        public void RecuperarParadasPorLineaParaCuandoLlegaAsync(int codLinea, object userState) {
            if ((this.RecuperarParadasPorLineaParaCuandoLlegaOperationCompleted == null)) {
                this.RecuperarParadasPorLineaParaCuandoLlegaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRecuperarParadasPorLineaParaCuandoLlegaOperationCompleted);
            }
            this.InvokeAsync("RecuperarParadasPorLineaParaCuandoLlega", new object[] {
                        codLinea}, this.RecuperarParadasPorLineaParaCuandoLlegaOperationCompleted, userState);
        }
        
        private void OnRecuperarParadasPorLineaParaCuandoLlegaOperationCompleted(object arg) {
            if ((this.RecuperarParadasPorLineaParaCuandoLlegaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RecuperarParadasPorLineaParaCuandoLlegaCompleted(this, new RecuperarParadasPorLineaParaCuandoLlegaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("UserDetailsValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RecuperarProximosArribosCLCompleto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ProximoArriboCLCompleto[] RecuperarProximosArribosCLCompleto(string identificadorParada, int codigoLineaParada, int codigoAplicacion, int codigoEntidad, string localidad) {
            object[] results = this.Invoke("RecuperarProximosArribosCLCompleto", new object[] {
                        identificadorParada,
                        codigoLineaParada,
                        codigoAplicacion,
                        codigoEntidad,
                        localidad});
            return ((ProximoArriboCLCompleto[])(results[0]));
        }
        
        /// <remarks/>
        public void RecuperarProximosArribosCLCompletoAsync(string identificadorParada, int codigoLineaParada, int codigoAplicacion, int codigoEntidad, string localidad) {
            this.RecuperarProximosArribosCLCompletoAsync(identificadorParada, codigoLineaParada, codigoAplicacion, codigoEntidad, localidad, null);
        }
        
        /// <remarks/>
        public void RecuperarProximosArribosCLCompletoAsync(string identificadorParada, int codigoLineaParada, int codigoAplicacion, int codigoEntidad, string localidad, object userState) {
            if ((this.RecuperarProximosArribosCLCompletoOperationCompleted == null)) {
                this.RecuperarProximosArribosCLCompletoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRecuperarProximosArribosCLCompletoOperationCompleted);
            }
            this.InvokeAsync("RecuperarProximosArribosCLCompleto", new object[] {
                        identificadorParada,
                        codigoLineaParada,
                        codigoAplicacion,
                        codigoEntidad,
                        localidad}, this.RecuperarProximosArribosCLCompletoOperationCompleted, userState);
        }
        
        private void OnRecuperarProximosArribosCLCompletoOperationCompleted(object arg) {
            if ((this.RecuperarProximosArribosCLCompletoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RecuperarProximosArribosCLCompletoCompleted(this, new RecuperarProximosArribosCLCompletoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("UserDetailsValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RecuperarProximosArribosSMP", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ProximoArriboSMP[] RecuperarProximosArribosSMP(string identificadorParada, string codigoLineaParadas, int codigoAplicacion, string localidad) {
            object[] results = this.Invoke("RecuperarProximosArribosSMP", new object[] {
                        identificadorParada,
                        codigoLineaParadas,
                        codigoAplicacion,
                        localidad});
            return ((ProximoArriboSMP[])(results[0]));
        }
        
        /// <remarks/>
        public void RecuperarProximosArribosSMPAsync(string identificadorParada, string codigoLineaParadas, int codigoAplicacion, string localidad) {
            this.RecuperarProximosArribosSMPAsync(identificadorParada, codigoLineaParadas, codigoAplicacion, localidad, null);
        }
        
        /// <remarks/>
        public void RecuperarProximosArribosSMPAsync(string identificadorParada, string codigoLineaParadas, int codigoAplicacion, string localidad, object userState) {
            if ((this.RecuperarProximosArribosSMPOperationCompleted == null)) {
                this.RecuperarProximosArribosSMPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRecuperarProximosArribosSMPOperationCompleted);
            }
            this.InvokeAsync("RecuperarProximosArribosSMP", new object[] {
                        identificadorParada,
                        codigoLineaParadas,
                        codigoAplicacion,
                        localidad}, this.RecuperarProximosArribosSMPOperationCompleted, userState);
        }
        
        private void OnRecuperarProximosArribosSMPOperationCompleted(object arg) {
            if ((this.RecuperarProximosArribosSMPCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RecuperarProximosArribosSMPCompleted(this, new RecuperarProximosArribosSMPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("UserDetailsValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RecuperarRecorridoParaMapaPorEntidadYLinea", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TresPropiedades[] RecuperarRecorridoParaMapaPorEntidadYLinea(int codigoEntidad, int codigoLineaParada) {
            object[] results = this.Invoke("RecuperarRecorridoParaMapaPorEntidadYLinea", new object[] {
                        codigoEntidad,
                        codigoLineaParada});
            return ((TresPropiedades[])(results[0]));
        }
        
        /// <remarks/>
        public void RecuperarRecorridoParaMapaPorEntidadYLineaAsync(int codigoEntidad, int codigoLineaParada) {
            this.RecuperarRecorridoParaMapaPorEntidadYLineaAsync(codigoEntidad, codigoLineaParada, null);
        }
        
        /// <remarks/>
        public void RecuperarRecorridoParaMapaPorEntidadYLineaAsync(int codigoEntidad, int codigoLineaParada, object userState) {
            if ((this.RecuperarRecorridoParaMapaPorEntidadYLineaOperationCompleted == null)) {
                this.RecuperarRecorridoParaMapaPorEntidadYLineaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRecuperarRecorridoParaMapaPorEntidadYLineaOperationCompleted);
            }
            this.InvokeAsync("RecuperarRecorridoParaMapaPorEntidadYLinea", new object[] {
                        codigoEntidad,
                        codigoLineaParada}, this.RecuperarRecorridoParaMapaPorEntidadYLineaOperationCompleted, userState);
        }
        
        private void OnRecuperarRecorridoParaMapaPorEntidadYLineaOperationCompleted(object arg) {
            if ((this.RecuperarRecorridoParaMapaPorEntidadYLineaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RecuperarRecorridoParaMapaPorEntidadYLineaCompleted(this, new RecuperarRecorridoParaMapaPorEntidadYLineaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("UserDetailsValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RecuperarRecorridoParaMapaAbrevYAmpliPorEntidadYLinea", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TresPropiedades[] RecuperarRecorridoParaMapaAbrevYAmpliPorEntidadYLinea(int codigoEntidad, int codigoLineaParada) {
            object[] results = this.Invoke("RecuperarRecorridoParaMapaAbrevYAmpliPorEntidadYLinea", new object[] {
                        codigoEntidad,
                        codigoLineaParada});
            return ((TresPropiedades[])(results[0]));
        }
        
        /// <remarks/>
        public void RecuperarRecorridoParaMapaAbrevYAmpliPorEntidadYLineaAsync(int codigoEntidad, int codigoLineaParada) {
            this.RecuperarRecorridoParaMapaAbrevYAmpliPorEntidadYLineaAsync(codigoEntidad, codigoLineaParada, null);
        }
        
        /// <remarks/>
        public void RecuperarRecorridoParaMapaAbrevYAmpliPorEntidadYLineaAsync(int codigoEntidad, int codigoLineaParada, object userState) {
            if ((this.RecuperarRecorridoParaMapaAbrevYAmpliPorEntidadYLineaOperationCompleted == null)) {
                this.RecuperarRecorridoParaMapaAbrevYAmpliPorEntidadYLineaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRecuperarRecorridoParaMapaAbrevYAmpliPorEntidadYLineaOperationCompleted);
            }
            this.InvokeAsync("RecuperarRecorridoParaMapaAbrevYAmpliPorEntidadYLinea", new object[] {
                        codigoEntidad,
                        codigoLineaParada}, this.RecuperarRecorridoParaMapaAbrevYAmpliPorEntidadYLineaOperationCompleted, userState);
        }
        
        private void OnRecuperarRecorridoParaMapaAbrevYAmpliPorEntidadYLineaOperationCompleted(object arg) {
            if ((this.RecuperarRecorridoParaMapaAbrevYAmpliPorEntidadYLineaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RecuperarRecorridoParaMapaAbrevYAmpliPorEntidadYLineaCompleted(this, new RecuperarRecorridoParaMapaAbrevYAmpliPorEntidadYLineaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("UserDetailsValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RecuperarTodasEmpresasAMigrar", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RecuperarTodasEmpresasAMigrar(int codigoEntidad, int codigoLineaParada) {
            object[] results = this.Invoke("RecuperarTodasEmpresasAMigrar", new object[] {
                        codigoEntidad,
                        codigoLineaParada});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RecuperarTodasEmpresasAMigrarAsync(int codigoEntidad, int codigoLineaParada) {
            this.RecuperarTodasEmpresasAMigrarAsync(codigoEntidad, codigoLineaParada, null);
        }
        
        /// <remarks/>
        public void RecuperarTodasEmpresasAMigrarAsync(int codigoEntidad, int codigoLineaParada, object userState) {
            if ((this.RecuperarTodasEmpresasAMigrarOperationCompleted == null)) {
                this.RecuperarTodasEmpresasAMigrarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRecuperarTodasEmpresasAMigrarOperationCompleted);
            }
            this.InvokeAsync("RecuperarTodasEmpresasAMigrar", new object[] {
                        codigoEntidad,
                        codigoLineaParada}, this.RecuperarTodasEmpresasAMigrarOperationCompleted, userState);
        }
        
        private void OnRecuperarTodasEmpresasAMigrarOperationCompleted(object arg) {
            if ((this.RecuperarTodasEmpresasAMigrarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RecuperarTodasEmpresasAMigrarCompleted(this, new RecuperarTodasEmpresasAMigrarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/", IsNullable=false)]
    public partial class UserDetails : System.Web.Services.Protocols.SoapHeader {
        
        private string userNameField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ProximoArriboSMP {
        
        private string lineaField;
        
        private string abreviaturaBanderaField;
        
        private string banderaField;
        
        private string arriboField;
        
        private string latitudField;
        
        private string longitudField;
        
        private string latitudParadaField;
        
        private string longitudParadaField;
        
        private string identificadorCocheField;
        
        private string identificadorChoferField;
        
        private string desvioHorarioField;
        
        private string ultimaFechaGPSField;
        
        /// <remarks/>
        public string linea {
            get {
                return this.lineaField;
            }
            set {
                this.lineaField = value;
            }
        }
        
        /// <remarks/>
        public string abreviaturaBandera {
            get {
                return this.abreviaturaBanderaField;
            }
            set {
                this.abreviaturaBanderaField = value;
            }
        }
        
        /// <remarks/>
        public string bandera {
            get {
                return this.banderaField;
            }
            set {
                this.banderaField = value;
            }
        }
        
        /// <remarks/>
        public string arribo {
            get {
                return this.arriboField;
            }
            set {
                this.arriboField = value;
            }
        }
        
        /// <remarks/>
        public string latitud {
            get {
                return this.latitudField;
            }
            set {
                this.latitudField = value;
            }
        }
        
        /// <remarks/>
        public string longitud {
            get {
                return this.longitudField;
            }
            set {
                this.longitudField = value;
            }
        }
        
        /// <remarks/>
        public string latitudParada {
            get {
                return this.latitudParadaField;
            }
            set {
                this.latitudParadaField = value;
            }
        }
        
        /// <remarks/>
        public string longitudParada {
            get {
                return this.longitudParadaField;
            }
            set {
                this.longitudParadaField = value;
            }
        }
        
        /// <remarks/>
        public string identificadorCoche {
            get {
                return this.identificadorCocheField;
            }
            set {
                this.identificadorCocheField = value;
            }
        }
        
        /// <remarks/>
        public string identificadorChofer {
            get {
                return this.identificadorChoferField;
            }
            set {
                this.identificadorChoferField = value;
            }
        }
        
        /// <remarks/>
        public string desvioHorario {
            get {
                return this.desvioHorarioField;
            }
            set {
                this.desvioHorarioField = value;
            }
        }
        
        /// <remarks/>
        public string ultimaFechaGPS {
            get {
                return this.ultimaFechaGPSField;
            }
            set {
                this.ultimaFechaGPSField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ProximoArriboCLCompleto {
        
        private string lineaField;
        
        private string abreviaturaBanderaField;
        
        private string abreviaturaAmpliadaBanderaField;
        
        private string arriboField;
        
        private string esAdaptadoField;
        
        private string latitudField;
        
        private string longitudField;
        
        private string latitudParadaField;
        
        private string longitudParadaField;
        
        /// <remarks/>
        public string linea {
            get {
                return this.lineaField;
            }
            set {
                this.lineaField = value;
            }
        }
        
        /// <remarks/>
        public string abreviaturaBandera {
            get {
                return this.abreviaturaBanderaField;
            }
            set {
                this.abreviaturaBanderaField = value;
            }
        }
        
        /// <remarks/>
        public string abreviaturaAmpliadaBandera {
            get {
                return this.abreviaturaAmpliadaBanderaField;
            }
            set {
                this.abreviaturaAmpliadaBanderaField = value;
            }
        }
        
        /// <remarks/>
        public string arribo {
            get {
                return this.arriboField;
            }
            set {
                this.arriboField = value;
            }
        }
        
        /// <remarks/>
        public string esAdaptado {
            get {
                return this.esAdaptadoField;
            }
            set {
                this.esAdaptadoField = value;
            }
        }
        
        /// <remarks/>
        public string latitud {
            get {
                return this.latitudField;
            }
            set {
                this.latitudField = value;
            }
        }
        
        /// <remarks/>
        public string longitud {
            get {
                return this.longitudField;
            }
            set {
                this.longitudField = value;
            }
        }
        
        /// <remarks/>
        public string latitudParada {
            get {
                return this.latitudParadaField;
            }
            set {
                this.latitudParadaField = value;
            }
        }
        
        /// <remarks/>
        public string longitudParada {
            get {
                return this.longitudParadaField;
            }
            set {
                this.longitudParadaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ParadaCompleta {
        
        private string identificadorField;
        
        private string descripcionField;
        
        private string sentidoField;
        
        private string callePrincipalField;
        
        private string calleSecundariaField;
        
        private string latitudField;
        
        private string longitudField;
        
        /// <remarks/>
        public string identificador {
            get {
                return this.identificadorField;
            }
            set {
                this.identificadorField = value;
            }
        }
        
        /// <remarks/>
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
        
        /// <remarks/>
        public string sentido {
            get {
                return this.sentidoField;
            }
            set {
                this.sentidoField = value;
            }
        }
        
        /// <remarks/>
        public string callePrincipal {
            get {
                return this.callePrincipalField;
            }
            set {
                this.callePrincipalField = value;
            }
        }
        
        /// <remarks/>
        public string calleSecundaria {
            get {
                return this.calleSecundariaField;
            }
            set {
                this.calleSecundariaField = value;
            }
        }
        
        /// <remarks/>
        public string latitud {
            get {
                return this.latitudField;
            }
            set {
                this.latitudField = value;
            }
        }
        
        /// <remarks/>
        public string longitud {
            get {
                return this.longitudField;
            }
            set {
                this.longitudField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ProximoArribo {
        
        private string lineaField;
        
        private string banderaField;
        
        private string arriboField;
        
        private string latitudField;
        
        private string longitudField;
        
        private string latitudParadaField;
        
        private string longitudParadaField;
        
        /// <remarks/>
        public string linea {
            get {
                return this.lineaField;
            }
            set {
                this.lineaField = value;
            }
        }
        
        /// <remarks/>
        public string bandera {
            get {
                return this.banderaField;
            }
            set {
                this.banderaField = value;
            }
        }
        
        /// <remarks/>
        public string arribo {
            get {
                return this.arriboField;
            }
            set {
                this.arriboField = value;
            }
        }
        
        /// <remarks/>
        public string latitud {
            get {
                return this.latitudField;
            }
            set {
                this.latitudField = value;
            }
        }
        
        /// <remarks/>
        public string longitud {
            get {
                return this.longitudField;
            }
            set {
                this.longitudField = value;
            }
        }
        
        /// <remarks/>
        public string latitudParada {
            get {
                return this.latitudParadaField;
            }
            set {
                this.latitudParadaField = value;
            }
        }
        
        /// <remarks/>
        public string longitudParada {
            get {
                return this.longitudParadaField;
            }
            set {
                this.longitudParadaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ParadaConBandera {
        
        private string codigoField;
        
        private string identificadorField;
        
        private string descripcionField;
        
        private string abreviaturaBanderaField;
        
        private string abreviaturaAmpliadaBanderaField;
        
        /// <remarks/>
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        public string identificador {
            get {
                return this.identificadorField;
            }
            set {
                this.identificadorField = value;
            }
        }
        
        /// <remarks/>
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
        
        /// <remarks/>
        public string abreviaturaBandera {
            get {
                return this.abreviaturaBanderaField;
            }
            set {
                this.abreviaturaBanderaField = value;
            }
        }
        
        /// <remarks/>
        public string abreviaturaAmpliadaBandera {
            get {
                return this.abreviaturaAmpliadaBanderaField;
            }
            set {
                this.abreviaturaAmpliadaBanderaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Parada {
        
        private string codigoField;
        
        private string identificadorField;
        
        private string descripcionField;
        
        /// <remarks/>
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        public string identificador {
            get {
                return this.identificadorField;
            }
            set {
                this.identificadorField = value;
            }
        }
        
        /// <remarks/>
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Simple {
        
        private string codigoField;
        
        private string descripcionField;
        
        /// <remarks/>
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TresPropiedades {
        
        private string descripcionAField;
        
        private string descripcionBField;
        
        private string descripcionCField;
        
        /// <remarks/>
        public string descripcionA {
            get {
                return this.descripcionAField;
            }
            set {
                this.descripcionAField = value;
            }
        }
        
        /// <remarks/>
        public string descripcionB {
            get {
                return this.descripcionBField;
            }
            set {
                this.descripcionBField = value;
            }
        }
        
        /// <remarks/>
        public string descripcionC {
            get {
                return this.descripcionCField;
            }
            set {
                this.descripcionCField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Localidad {
        
        private string localidadGoogleField;
        
        private string provinciaGoogleField;
        
        private string paisGoogleField;
        
        /// <remarks/>
        public string localidadGoogle {
            get {
                return this.localidadGoogleField;
            }
            set {
                this.localidadGoogleField = value;
            }
        }
        
        /// <remarks/>
        public string provinciaGoogle {
            get {
                return this.provinciaGoogleField;
            }
            set {
                this.provinciaGoogleField = value;
            }
        }
        
        /// <remarks/>
        public string paisGoogle {
            get {
                return this.paisGoogleField;
            }
            set {
                this.paisGoogleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void RecuperarLocalidadesPorEntidadCompletedEventHandler(object sender, RecuperarLocalidadesPorEntidadCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RecuperarLocalidadesPorEntidadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RecuperarLocalidadesPorEntidadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Localidad[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Localidad[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void RecuperarLineaPorLocalidadCompletedEventHandler(object sender, RecuperarLineaPorLocalidadCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RecuperarLineaPorLocalidadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RecuperarLineaPorLocalidadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TresPropiedades[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TresPropiedades[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void RecuperarLineaPorEntidadCompletedEventHandler(object sender, RecuperarLineaPorEntidadCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RecuperarLineaPorEntidadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RecuperarLineaPorEntidadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Simple[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Simple[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void RecuperarLineasPorCodigoEmpresaCompletedEventHandler(object sender, RecuperarLineasPorCodigoEmpresaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RecuperarLineasPorCodigoEmpresaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RecuperarLineasPorCodigoEmpresaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Simple[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Simple[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void RecuperarLineaPorCuandoLlegaCompletedEventHandler(object sender, RecuperarLineaPorCuandoLlegaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RecuperarLineaPorCuandoLlegaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RecuperarLineaPorCuandoLlegaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TresPropiedades[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TresPropiedades[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void RecuperarCallesPrincipalPorLineaCompletedEventHandler(object sender, RecuperarCallesPrincipalPorLineaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RecuperarCallesPrincipalPorLineaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RecuperarCallesPrincipalPorLineaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Simple[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Simple[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void RecuperarInterseccionPorLineaYCalleCompletedEventHandler(object sender, RecuperarInterseccionPorLineaYCalleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RecuperarInterseccionPorLineaYCalleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RecuperarInterseccionPorLineaYCalleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Simple[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Simple[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void RecuperarParadasPorCalleEInterseccionCompletedEventHandler(object sender, RecuperarParadasPorCalleEInterseccionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RecuperarParadasPorCalleEInterseccionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RecuperarParadasPorCalleEInterseccionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Parada[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Parada[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void RecuperarParadasPorLineaCalleEInterseccionCompletedEventHandler(object sender, RecuperarParadasPorLineaCalleEInterseccionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RecuperarParadasPorLineaCalleEInterseccionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RecuperarParadasPorLineaCalleEInterseccionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Parada[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Parada[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void RecuperarParadasConBanderaPorLineaCalleEInterseccionCompletedEventHandler(object sender, RecuperarParadasConBanderaPorLineaCalleEInterseccionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RecuperarParadasConBanderaPorLineaCalleEInterseccionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RecuperarParadasConBanderaPorLineaCalleEInterseccionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ParadaConBandera[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ParadaConBandera[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void RecuperarProximosArribosCompletedEventHandler(object sender, RecuperarProximosArribosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RecuperarProximosArribosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RecuperarProximosArribosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ProximoArribo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ProximoArribo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void RecuperarParadasPorLineaParaCuandoLlegaCompletedEventHandler(object sender, RecuperarParadasPorLineaParaCuandoLlegaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RecuperarParadasPorLineaParaCuandoLlegaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RecuperarParadasPorLineaParaCuandoLlegaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ParadaCompleta[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ParadaCompleta[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void RecuperarProximosArribosCLCompletoCompletedEventHandler(object sender, RecuperarProximosArribosCLCompletoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RecuperarProximosArribosCLCompletoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RecuperarProximosArribosCLCompletoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ProximoArriboCLCompleto[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ProximoArriboCLCompleto[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void RecuperarProximosArribosSMPCompletedEventHandler(object sender, RecuperarProximosArribosSMPCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RecuperarProximosArribosSMPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RecuperarProximosArribosSMPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ProximoArriboSMP[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ProximoArriboSMP[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void RecuperarRecorridoParaMapaPorEntidadYLineaCompletedEventHandler(object sender, RecuperarRecorridoParaMapaPorEntidadYLineaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RecuperarRecorridoParaMapaPorEntidadYLineaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RecuperarRecorridoParaMapaPorEntidadYLineaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TresPropiedades[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TresPropiedades[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void RecuperarRecorridoParaMapaAbrevYAmpliPorEntidadYLineaCompletedEventHandler(object sender, RecuperarRecorridoParaMapaAbrevYAmpliPorEntidadYLineaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RecuperarRecorridoParaMapaAbrevYAmpliPorEntidadYLineaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RecuperarRecorridoParaMapaAbrevYAmpliPorEntidadYLineaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TresPropiedades[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TresPropiedades[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void RecuperarTodasEmpresasAMigrarCompletedEventHandler(object sender, RecuperarTodasEmpresasAMigrarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RecuperarTodasEmpresasAMigrarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RecuperarTodasEmpresasAMigrarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591